version: '3.8'
services:
  workspace:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: vscode

  localai:
    image: localai/localai:latest
    container_name: agora-localai-codespace
    ports:
      - "8080:8080"
    environment:
      - THREADS=2
      - MODELS_PATH=/workspace/localai-models
      - CORS=true
      - CORS_ALLOW_ORIGINS=*
    volumes:
      - ..:/workspace:cached
    restart: unless-stopped
